// src/common/enums/response-message.enum.ts
export enum ResponseMessageEnum {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_CREATED = 'USER_CREATED',
  USER_INVITED = 'USER_INVITED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  GENERIC_ERROR = 'GENERIC_ERROR',
  PASSWORD_CONFIRMATION_MISMATCH = "PASSWORD_CONFIRMATION_MISMATCH",
  INVALID_OR_EXPIRED_CODE = 'INVALID_OR_EXPIRED_CODE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
